USE [master]
GO

/****** Object:  Database [SWCDotNetCohort]    Script Date: 7/14/2015 12:44:26 PM ******/
CREATE DATABASE [SWCDotNetCohort]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SWCDotNetCohort', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQL2014\MSSQL\DATA\SWCDotNetCohort.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SWCDotNetCohort_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQL2014\MSSQL\DATA\SWCDotNetCohort_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SWCDotNetCohort] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SWCDotNetCohort].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SWCDotNetCohort] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SWCDotNetCohort] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SWCDotNetCohort] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SWCDotNetCohort] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SWCDotNetCohort] SET ARITHABORT OFF 
GO

ALTER DATABASE [SWCDotNetCohort] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SWCDotNetCohort] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SWCDotNetCohort] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SWCDotNetCohort] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SWCDotNetCohort] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SWCDotNetCohort] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SWCDotNetCohort] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SWCDotNetCohort] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SWCDotNetCohort] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SWCDotNetCohort] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SWCDotNetCohort] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SWCDotNetCohort] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SWCDotNetCohort] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SWCDotNetCohort] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SWCDotNetCohort] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SWCDotNetCohort] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SWCDotNetCohort] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SWCDotNetCohort] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SWCDotNetCohort] SET  MULTI_USER 
GO

ALTER DATABASE [SWCDotNetCohort] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SWCDotNetCohort] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SWCDotNetCohort] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SWCDotNetCohort] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SWCDotNetCohort] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SWCDotNetCohort] SET  READ_WRITE 
GO


